### ISSUE TITLE
Clarify whether fields can be added to groups/dsets with only `data_type_inc`

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf-schema-language#13]
Raised in https://github.com/hdmf-dev/hdmf/pull/542 in the context of how extra fields are treated.

It is not clear in the documentation whether the schema language allows new fields for groups/datasets defined with only a `data_type_inc`. We should clarify this in the documentation.

It is my understanding that it is allowed (though perhaps not recommended) for fields to be added to groups/datasets defined with only a `data_type_inc`. 

For example: a new group may contain a dataset with:
```yaml
- data_type_def: MyTable
  datasets:
  - name: new_column
    data_type_inc: VectorData
    attributes:
    - name: new_attr
      dtype: text
      doc: a new attribute
```

A concrete example is in the Units table in NWB: https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/core/nwb.misc.yaml#L187-L199

The `resolution` attribute is added to the base `VectorData` definition.

Or a new group may be defined as:
```yaml
- data_type_def: MyContainer
  groups:
  - name: new_group
    data_type_inc: Container
    groups:
    - name: new_subgroup
      data_type_inc: Container
      doc: a new subgroup
    # also add new datasets, new links, and new attributes
```

A related but not fully matching example is the 'electrodes' table in the NWBFile: https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/core/nwb.file.yaml#L269

The 'electrodes' table lacks a data_type_def but specifies many named `VectorData` types. However, this differs from the above because `DynamicTable` explicitly allows `quantity: *` of `data_type_inc: VectorData` without a name specified. 

Note that a group/dataset defined with only a `data_type_inc` may have a different doc, quantity, dims, shape, and sometimes even dtype than in the `data_type_def` definition, as long as these are compatible with the included spec (e.g., a square is a special case of a rectangle). This should also be clarified in the documentation and fully supported in HDMF.

If adding fields to types with only `data_type_inc` is not allowed, then the NWB schema should be amended.
If the above is allowed, then the HDMF validator should be amended to validate against the spec with any additions to the included type.
